# Generated by Django 4.1.9 on 2023-07-22 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_training_trainingapplied_jobapplied_employerdetail_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobapplied',
            name='slug',
        ),
    ]
