# Generated by Django 4.1.9 on 2023-07-23 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_remove_jobapplied_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainingapplied',
            name='slug',
        ),
    ]
