# Generated by Django 4.1.9 on 2023-07-23 17:43

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0004_remove_trainingapplied_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainingapplied',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='trainingapplied',
            name='start_time',
        ),
        migrations.AddField(
            model_name='training',
            name='end_time',
            field=models.DateField(default=datetime.datetime(2023, 7, 23, 23, 28, 9, 881536)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='training',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
