# Generated by Django 4.1.9 on 2023-07-24 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_userskills_alter_workexperience_user_user_skills'),
        ('job', '0005_remove_trainingapplied_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employerdetail',
            name='address',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employerdetail',
            name='logo',
            field=models.FileField(blank=True, null=True, upload_to='logo/'),
        ),
        migrations.AddField(
            model_name='job',
            name='skills_required',
            field=models.ManyToManyField(to='users.userskills'),
        ),
    ]
